import type { WorkspacePrComment } from "../../contracts/git.ts";

/**
 * Turn a sanitized-away HTML `<table>` into a GFM table so a bot's status
 * matrix (Vercel, etc.) renders as a real table instead of a pile of cells.
 * Inline markup inside cells has already been folded to markdown by the time
 * this runs; unknown tags are stripped by the caller afterwards.
 */
function htmlTableToMarkdown(tableHtml: string): string {
  const rows = [...tableHtml.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)].map(
    (match) => match[1] ?? "",
  );
  const cellsFor = (row: string) =>
    [...row.matchAll(/<(?:td|th)[^>]*>([\s\S]*?)<\/(?:td|th)>/gi)].map((cell) =>
      (cell[1] ?? "")
        // Any tag still here wasn't folded by the inline passes; drop it so a
        // later newline replacement can't split the cell's markdown.
        .replace(/<[^>]+>/g, "")
        .replace(/\s+/g, " ")
        .replace(/\|/g, "\\|")
        .trim(),
    );
  const parsed = rows.map(cellsFor).filter((cells) => cells.length > 0);
  if (parsed.length === 0) return "\n";

  const width = Math.max(...parsed.map((cells) => cells.length));
  const pad = (cells: string[]) => [...cells, ...Array<string>(width - cells.length).fill("")];
  const toLine = (cells: string[]) => `| ${pad(cells).join(" | ")} |`;
  const [header, ...rest] = parsed;
  const separator = `| ${Array.from({ length: width }, () => "---").join(" | ")} |`;
  return `\n\n${[toLine(header!), separator, ...rest.map(toLine)].join("\n")}\n\n`;
}

/**
 * Review bots post HTML (`<h3>`, `<details>`, `<code>`), which the sanitized
 * markdown renderer drops. Fold the common tags into markdown so a comment
 * reads the way it does on GitHub, and strip the rest.
 */
export function commentToMarkdown(body: string): string {
  return (
    body
      .replace(/<!--[\s\S]*?-->/g, "")
      .replace(/<br\s*\/?>/gi, "\n")
      .replace(/<h([1-6])[^>]*>([\s\S]*?)<\/h\1>/gi, (_m, level: string, text: string) => {
        return `\n${"#".repeat(Number(level))} ${text.trim()}\n`;
      })
      .replace(/<summary[^>]*>([\s\S]*?)<\/summary>/gi, "\n**$1**\n")
      .replace(/<\/?details[^>]*>/gi, "\n")
      .replace(
        /<a\s+[^>]*href=["']([^"']*)["'][^>]*>([\s\S]*?)<\/a>/gi,
        (_m, href: string, text: string) => {
          // Anchors wrapping only images/decorations carry no text; keep the URL
          // out of the markdown (an empty `[](url)` would just be link noise).
          const plain = text.replace(/<[^>]+>/g, "").trim();
          return plain ? `[${text}](${href})` : "";
        },
      )
      .replace(/<(b|strong)>([\s\S]*?)<\/\1>/gi, "**$2**")
      .replace(/<(i|em)>([\s\S]*?)<\/\1>/gi, "_$2_")
      .replace(/<code>([\s\S]*?)<\/code>/gi, "`$1`")
      // A status badge image immediately before a link with the same label is
      // redundant (e.g. Vercel's `![Ready](dot.svg) [Ready](url)`); drop the
      // image so the cell reads as one line instead of stacking the dot on top.
      .replace(
        /!\[([^\]]+)\]\([^)]*\)(\s*)\[([^\]]+)\]\(/g,
        (match, alt: string, gap: string, label: string) =>
          alt.trim().toLowerCase() === label.trim().toLowerCase() ? `${gap}[${label}](` : match,
      )
      .replace(/<table[^>]*>[\s\S]*?<\/table>/gi, (table) => htmlTableToMarkdown(table))
      // Block-only tags become line breaks. Inline tags (img, span, sup, …) are
      // left for the generic strip below — turning them into newlines would break
      // any markdown table row that embeds HTML in a cell.
      .replace(/<\/?(p|div|ul|ol|li|table|thead|tbody|tr|td|th|blockquote)[^>]*>/gi, "\n")
      .replace(/<[^>]+>/g, "")
      .replace(/\n{3,}/g, "\n\n")
      .trim()
  );
}

/**
 * Drop a bot's autogenerated appendix from a PR body — e.g. CodeRabbit's
 * `<!-- This is an auto-generated comment: … coderabbit.ai -->` block and
 * everything after it — so the Check tab shows the author's description only.
 */
export function stripAutogeneratedBody(body: string): string {
  return body.replace(/<!--[\s\S]*?auto-generated[\s\S]*?-->[\s\S]*$/i, "").trim();
}

/**
 * Drop a leading markdown heading from a PR body when it just repeats the PR
 * title, so a panel that shows the title doesn't print it twice.
 */
export function stripDuplicateTitle(body: string, title: string): string {
  const match = body.match(/^[ \t]*#{1,6}[ \t]+([^\n]+?)[ \t]*(?:\n|$)/);
  if (!match) return body;
  const normalize = (value: string) =>
    value
      .replace(/[*_`#>]/g, "")
      .replace(/\s+/g, " ")
      .trim()
      .toLowerCase();
  if (normalize(match[1]!) !== normalize(title)) return body;
  return body.slice((match.index ?? 0) + match[0].length).replace(/^\s+/, "");
}

/** First meaningful line of a comment body, one line, capped. */
export function commentPreview(body: string, max = 140): string {
  const cleaned = commentToMarkdown(body)
    .replace(/[#*_`>|]+/g, " ")
    .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1")
    .replace(/\s+/g, " ")
    .trim();
  return cleaned.slice(0, max);
}

/**
 * Card title: `path:line` for inline review comments, else the comment's
 * own heading when it opens with one, else its first sentence.
 */
export function commentTitle(comment: Pick<WorkspacePrComment, "body" | "path" | "line">): string {
  if (comment.path) return `${comment.path}${comment.line ? `:${comment.line}` : ""}`;
  const markdown = commentToMarkdown(comment.body);
  const heading = markdown.match(/^#{1,6}\s+(.+)$/m)?.[1]?.trim();
  if (heading) return heading.replace(/[*_`]/g, "").slice(0, 80);
  const firstLine =
    markdown
      .split("\n")
      .map((line) => line.trim())
      // Skip link-reference definitions (e.g. Vercel's `[vc]: #…` metadata),
      // which GitHub renders invisibly.
      .find((line) => line && !/^\[[^\]]+\]:\s*\S/.test(line)) ?? "";
  const sentence = firstLine.split(/(?<=[.!?])\s/)[0] ?? firstLine;
  return commentPreview(sentence, 80) || "Comment";
}

export type CommentSeverity = "high" | "medium" | "low";

/** Inline review comments carry a `path`; general bot comments don't. */
export function isInlineComment(comment: Pick<WorkspacePrComment, "path">): boolean {
  return Boolean(comment.path);
}

const SEVERITY_RULES: Array<{ level: CommentSeverity; pattern: RegExp }> = [
  { level: "high", pattern: /\b(critical|high|blocker|bugs?|security)\b|vulnerab/i },
  { level: "medium", pattern: /\b(warning|medium|rule violation)\b/i },
  { level: "low", pattern: /\b(nitpicks?|low|suggestions?|styles?|minor)\b/i },
];

/**
 * Best-effort severity for a bot comment, read from its opening heading /
 * summary line (where every bot we've seen states it). Conservative: returns
 * null rather than guessing from the body prose.
 */
export function commentSeverity(comment: Pick<WorkspacePrComment, "body">): CommentSeverity | null {
  const opening = commentToMarkdown(comment.body).slice(0, 280);
  for (const rule of SEVERITY_RULES) if (rule.pattern.test(opening)) return rule.level;
  return null;
}

const SEVERITY_RANK: Record<CommentSeverity, number> = { high: 3, medium: 2, low: 1 };

/** Highest severity across a group, for the bot's accordion header. */
export function highestSeverity(comments: WorkspacePrComment[]): CommentSeverity | null {
  let best: CommentSeverity | null = null;
  for (const comment of comments) {
    const level = commentSeverity(comment);
    if (level && (best === null || SEVERITY_RANK[level] > SEVERITY_RANK[best])) best = level;
  }
  return best;
}

/** Comments grouped by author, in the order authors first appear. */
export function groupCommentsByAuthor(
  comments: WorkspacePrComment[],
): Array<{ author: string; avatarUrl: string | null; comments: WorkspacePrComment[] }> {
  const groups = new Map<
    string,
    { author: string; avatarUrl: string | null; comments: WorkspacePrComment[] }
  >();
  for (const comment of comments) {
    const group = groups.get(comment.author);
    if (group) {
      group.comments.push(comment);
      group.avatarUrl ??= comment.avatarUrl;
    } else {
      groups.set(comment.author, {
        author: comment.author,
        avatarUrl: comment.avatarUrl,
        comments: [comment],
      });
    }
  }
  return [...groups.values()];
}

export function sortComments(
  comments: WorkspacePrComment[],
  order: "latest" | "oldest",
): WorkspacePrComment[] {
  const stamp = (comment: WorkspacePrComment) => Date.parse(comment.createdAt) || 0;
  return [...comments].sort((a, b) =>
    order === "latest" ? stamp(b) - stamp(a) : stamp(a) - stamp(b),
  );
}
