import { describe, expect, test } from "vitest";
import {
  commentPreview,
  commentSeverity,
  commentTitle,
  commentToMarkdown,
  groupCommentsByAuthor,
  highestSeverity,
  isInlineComment,
  sortComments,
  stripAutogeneratedBody,
  stripDuplicateTitle,
} from "./pr-comment-text";

const comment = (over: Partial<Parameters<typeof sortComments>[0][number]>) => ({
  id: "x",
  author: "a",
  avatarUrl: null,
  body: "",
  url: null,
  createdAt: "",
  path: null,
  line: null,
  ...over,
});

describe("commentToMarkdown", () => {
  test("folds bot html into markdown", () => {
    expect(
      commentToMarkdown(
        "<!-- auto --><h3>PR Summary</h3><details><summary>More</summary><code>x</code> and <b>y</b><br>z</details>",
      ),
    ).toBe("### PR Summary\n\n**More**\n`x` and **y**\nz");
  });

  test("leaves plain markdown alone", () => {
    expect(commentToMarkdown("## Head\n\n- item")).toBe("## Head\n\n- item");
  });

  test("converts an html table into a gfm table", () => {
    expect(
      commentToMarkdown(
        "<table><thead><tr><th>Project</th><th>Deployment</th></tr></thead><tbody><tr><td>web</td><td>Ready</td></tr><tr><td>docs</td><td>Queued</td></tr></tbody></table>",
      ),
    ).toBe("| Project | Deployment |\n| --- | --- |\n| web | Ready |\n| docs | Queued |");
  });

  test("pads short html table rows to the widest row", () => {
    expect(
      commentToMarkdown("<table><tr><td>A</td><td>B</td></tr><tr><td>C</td></tr></table>"),
    ).toBe("| A | B |\n| --- | --- |\n| C |  |");
  });

  test("strips residual tags inside cells so links stay intact", () => {
    expect(
      commentToMarkdown(
        '<table><thead><tr><th>Project</th><th>Deployment</th></tr></thead><tbody><tr><td><a href="https://vercel.com/x"><span>omni</span></a></td><td>Ready</td></tr></tbody></table>',
      ),
    ).toBe("| Project | Deployment |\n| --- | --- |\n| [omni](https://vercel.com/x) | Ready |");
  });

  test("keeps a markdown table row intact when a cell embeds html", () => {
    const body =
      '| Project | Deployment |\n| --- | --- |\n| <a href="https://vercel.com/x"><sup><img src="a" alt="" /></sup></a> [omni](https://vercel.com/x) | ![Ready](https://v/ready.svg) |';
    expect(commentToMarkdown(body)).toBe(
      "| Project | Deployment |\n| --- | --- |\n|  [omni](https://vercel.com/x) | ![Ready](https://v/ready.svg) |",
    );
  });

  test("drops a status badge image duplicated by the link beside it", () => {
    expect(commentToMarkdown("![Ready](https://v/ready.svg) [Ready](https://v/x)")).toBe(
      "[Ready](https://v/x)",
    );
    // A lone image (no matching link) is left alone.
    expect(commentToMarkdown("![Ready](https://v/ready.svg)")).toBe(
      "![Ready](https://v/ready.svg)",
    );
  });
});

describe("stripAutogeneratedBody", () => {
  test("drops an autogenerated bot appendix", () => {
    expect(
      stripAutogeneratedBody(
        "Human body.\n\n<!-- This is an auto-generated comment: release notes by coderabbit.ai -->\n## Summary by CodeRabbit\nDetails",
      ),
    ).toBe("Human body.");
  });

  test("leaves a body with no bot appendix alone", () => {
    expect(stripAutogeneratedBody("Just the description.")).toBe("Just the description.");
  });
});

describe("stripDuplicateTitle", () => {
  test("removes a leading heading that repeats the title", () => {
    expect(stripDuplicateTitle("# Add Siri Intent\n\nBody text", "Add Siri Intent")).toBe(
      "Body text",
    );
    expect(stripDuplicateTitle("## add  siri intent\n\nBody", "Add Siri Intent")).toBe("Body");
  });

  test("keeps the body when the heading differs or there is none", () => {
    expect(stripDuplicateTitle("## Overview\n\nBody", "Add Siri Intent")).toBe(
      "## Overview\n\nBody",
    );
    expect(stripDuplicateTitle("Body only", "Add Siri Intent")).toBe("Body only");
  });
});

describe("commentPreview", () => {
  test("is a single stripped line, capped", () => {
    expect(commentPreview("<h3>PR Summary</h3>\n\n**Bold** `code` > quote")).toBe(
      "PR Summary Bold code quote",
    );
    expect(commentPreview("x".repeat(500))).toHaveLength(140);
  });
});

describe("isInlineComment / commentSeverity / highestSeverity", () => {
  test("inline comments are the ones with a path", () => {
    expect(isInlineComment({ path: "src/a.ts" })).toBe(true);
    expect(isInlineComment({ path: null })).toBe(false);
  });

  test("severity is read from the opening heading, else null", () => {
    expect(commentSeverity({ body: "<h3>🐞 Bugs (11)</h3>" })).toBe("high");
    expect(commentSeverity({ body: "### Nitpick\nminor thing" })).toBe("low");
    expect(commentSeverity({ body: "Everything looks fine here." })).toBeNull();
  });

  test("highestSeverity returns the most severe level in a group", () => {
    expect(
      highestSeverity([
        comment({ body: "### Nitpick\nminor" }),
        comment({ body: "Critical bug in auth" }),
      ]),
    ).toBe("high");
    expect(highestSeverity([])).toBeNull();
  });
});

describe("commentTitle", () => {
  test("inline comments use path:line", () => {
    expect(commentTitle({ body: "fix", path: "src/a.ts", line: 7 })).toBe("src/a.ts:7");
  });

  test("uses the opening heading when present, else the first sentence", () => {
    expect(
      commentTitle({ body: "<h3>Intent Is Not Packaged</h3>The build…", path: null, line: null }),
    ).toBe("Intent Is Not Packaged");
    expect(
      commentTitle({ body: "The build compiles it. But never links it.", path: null, line: null }),
    ).toBe("The build compiles it.");
  });

  test("skips invisible link-reference metadata lines", () => {
    expect(
      commentTitle({
        body: "[vc]: #abc==\n\nThe latest updates on your projects.",
        path: null,
        line: null,
      }),
    ).toBe("The latest updates on your projects.");
  });
});

describe("groupCommentsByAuthor / sortComments", () => {
  test("groups in first-seen order and sorts by time", () => {
    const list = [
      comment({ id: "1", author: "rabbit", createdAt: "2026-01-01T00:00:00Z" }),
      comment({ id: "2", author: "qodo", createdAt: "2026-01-02T00:00:00Z" }),
      comment({ id: "3", author: "rabbit", createdAt: "2026-01-03T00:00:00Z", avatarUrl: "u" }),
    ];
    const groups = groupCommentsByAuthor(list);
    expect(groups.map((g) => [g.author, g.comments.length, g.avatarUrl])).toEqual([
      ["rabbit", 2, "u"],
      ["qodo", 1, null],
    ]);
    expect(sortComments(groups[0]!.comments, "latest").map((c) => c.id)).toEqual(["3", "1"]);
    expect(sortComments(groups[0]!.comments, "oldest").map((c) => c.id)).toEqual(["1", "3"]);
  });
});
