import type { ComponentType } from "react";
import type { IconComponent, IconName, IconComponentProps } from "../icon-map";
import {
  IconChevronRight,
  IconChevronDown,
  IconColorPicker,
  IconX,
  IconCopy,
  IconMenu2,
  IconPoint,
  IconDeviceDesktop,
  IconSun,
  IconMoon,
  IconSquare,
  IconCircle,
  IconLibrary,
  IconClock,
  IconStar,
  IconSettings,
  IconPlus,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconSearch,
  IconLoader2,
  IconUsers,
  IconLock,
  IconMail,
  IconBell,
  IconShield,
  IconPalette,
  IconBulb,
  IconRocket,
  IconHeart,
  IconBrush,
  IconBrain,
  IconGlobe,
  IconUser,
  IconPhoto,
  IconLink,
  IconCheck,
  IconRotate2,
  IconPlayerPlay,
  IconPlayerPause,
  IconHome,
  IconMessageCircle,
  IconInbox,
  IconPencil,
  IconPlayerSkipForward,
  IconCornerDownRight,
} from "@tabler/icons-react";

function tabler(
  Icon: ComponentType<{ size?: number; stroke?: number; className?: string }>,
): IconComponent {
  return function TablerAdapter({ size, strokeWidth, className }: IconComponentProps) {
    return <Icon size={size} stroke={strokeWidth} className={className} />;
  };
}

export const tablerMap: Record<IconName, IconComponent> = {
  "chevron-right": tabler(IconChevronRight),
  "chevron-down": tabler(IconChevronDown),
  pipette: tabler(IconColorPicker),
  x: tabler(IconX),
  copy: tabler(IconCopy),
  menu: tabler(IconMenu2),
  dot: tabler(IconPoint),
  monitor: tabler(IconDeviceDesktop),
  sun: tabler(IconSun),
  moon: tabler(IconMoon),
  "rectangle-horizontal": tabler(IconSquare),
  circle: tabler(IconCircle),
  "square-library": tabler(IconLibrary),
  clock: tabler(IconClock),
  star: tabler(IconStar),
  settings: tabler(IconSettings),
  plus: tabler(IconPlus),
  "arrow-left": tabler(IconArrowLeft),
  "arrow-right": tabler(IconArrowRight),
  "arrow-up": tabler(IconArrowUp),
  search: tabler(IconSearch),
  loader: tabler(IconLoader2),
  users: tabler(IconUsers),
  lock: tabler(IconLock),
  mail: tabler(IconMail),
  bell: tabler(IconBell),
  shield: tabler(IconShield),
  palette: tabler(IconPalette),
  lightbulb: tabler(IconBulb),
  rocket: tabler(IconRocket),
  heart: tabler(IconHeart),
  paintbrush: tabler(IconBrush),
  brain: tabler(IconBrain),
  globe: tabler(IconGlobe),
  user: tabler(IconUser),
  image: tabler(IconPhoto),
  link: tabler(IconLink),
  check: tabler(IconCheck),
  "rotate-ccw": tabler(IconRotate2),
  play: tabler(IconPlayerPlay),
  pause: tabler(IconPlayerPause),
  home: tabler(IconHome),
  "message-circle": tabler(IconMessageCircle),
  inbox: tabler(IconInbox),
  pencil: tabler(IconPencil),
  "skip-forward": tabler(IconPlayerSkipForward),
  "corner-down-right": tabler(IconCornerDownRight),
};

export default tablerMap;
