import { useRef, useState, type ReactNode } from "react";
import { ArrowUpRight, Check, CircleNotch, Minus, X } from "@phosphor-icons/react";
import { WorkspacePrComments } from "@/components/workspace-pr-comments";
import type {
  WorkspaceGitStatus,
  WorkspacePrCheck,
  WorkspacePrComment,
  WorkspacePrDeployment,
} from "../../contracts/git.ts";
import { MarkdownRenderer } from "@/components/ui/markdown-renderer";
import { useContentOverflow } from "@/lib/use-content-overflow";
import { stripAutogeneratedBody, stripDuplicateTitle } from "@/lib/pr-comment-text";

/** One "todo" row under Git status: what blocks the PR and the button that clears it. */
export interface PrStatusItem {
  key: string;
  label: string;
  /** Green check instead of the empty circle. */
  done?: boolean;
  action?: { label: string; onClick: () => void; disabled?: boolean };
}

function StateIcon({
  state,
}: {
  state: WorkspacePrCheck["state"] | WorkspacePrDeployment["state"];
}) {
  switch (state) {
    case "passing":
    case "success":
      return <Check size={15} weight="bold" className="text-emerald-500" />;
    case "failing":
    case "failure":
      return <X size={15} weight="bold" className="text-destructive" />;
    case "skipped":
    case "inactive":
      return <Minus size={15} weight="bold" className="text-muted-foreground/50" />;
    default:
      return <CircleNotch size={15} weight="bold" className="animate-spin text-amber-500" />;
  }
}

/** A plain row: state glyph, name, outbound link. */
function LinkRow({ icon, label, url }: { icon: ReactNode; label: string; url: string | null }) {
  return (
    <li className="flex min-h-8 items-center gap-2.5 py-1 text-[13px]">
      <span className="flex w-4 shrink-0 items-center justify-center">{icon}</span>
      <span className="min-w-0 flex-1 truncate text-foreground" title={label}>
        {label}
      </span>
      {url ? (
        <button
          type="button"
          onClick={() => void window.omni.shell.openHttps(url).catch(() => {})}
          className="shrink-0 text-muted-foreground/70 transition-colors hover:text-foreground"
          title={url}
          aria-label={`Open ${label}`}
        >
          <ArrowUpRight size={13} />
        </button>
      ) : null}
    </li>
  );
}

function SectionTitle({ children }: { children: ReactNode }) {
  return <h3 className="text-sm font-semibold text-foreground">{children}</h3>;
}

const BODY_COLLAPSED_PX = 220;

export function WorkspacePrDetail({
  status,
  items: _items,
  onAddComments,
}: {
  status: WorkspaceGitStatus;
  /** Retained for callers; the header's tone already states the merge state. */
  items: PrStatusItem[];
  /** Hand comments to the agent; absent when no workspace thread can take them. */
  onAddComments?: (comments: WorkspacePrComment[]) => void;
}) {
  const pr = status.pr;
  const [bodyExpanded, setBodyExpanded] = useState(false);
  const bodyRef = useRef<HTMLDivElement | null>(null);
  // Rendered height, not character count, decides whether anything is clipped.
  const bodyClipped = useContentOverflow(bodyRef, [pr?.body, bodyExpanded]);
  if (!pr) return null;

  const body = stripDuplicateTitle(stripAutogeneratedBody(pr.body.trim()), pr.title);

  return (
    <div className="flex flex-col gap-6">
      {pr.title || body ? (
        <section className="flex flex-col gap-2">
          {pr.title ? (
            <h2 className="text-lg font-semibold leading-6 text-foreground">{pr.title}</h2>
          ) : null}
          {body ? (
            <div>
              <div
                ref={bodyRef}
                className="relative overflow-hidden"
                style={bodyExpanded ? undefined : { maxHeight: BODY_COLLAPSED_PX }}
              >
                <MarkdownRenderer className="text-[13px] leading-6 text-muted-foreground">
                  {body}
                </MarkdownRenderer>
                {!bodyExpanded && bodyClipped ? (
                  <div className="pointer-events-none absolute inset-x-0 bottom-0 h-8 bg-linear-to-t from-surface-1 to-transparent" />
                ) : null}
              </div>
              {!bodyExpanded && bodyClipped ? (
                <button
                  type="button"
                  onClick={() => setBodyExpanded(true)}
                  className="mx-auto mt-1 block text-[11px] text-muted-foreground/70 transition-colors hover:text-foreground"
                >
                  Show more
                </button>
              ) : null}
            </div>
          ) : null}
        </section>
      ) : null}

      {pr.deployments.length > 0 ? (
        <section className="flex flex-col gap-1.5">
          <SectionTitle>Deployments</SectionTitle>
          <ul className="flex flex-col">
            {pr.deployments.map((deployment, index) => (
              <LinkRow
                key={`${deployment.environment}-${index}`}
                icon={<StateIcon state={deployment.state} />}
                label={deployment.environment}
                url={deployment.url}
              />
            ))}
          </ul>
        </section>
      ) : null}

      <section className="flex flex-col gap-1.5">
        <SectionTitle>Checks</SectionTitle>
        {status.checks.length > 0 ? (
          <ul className="flex flex-col">
            {status.checks.map((check) => (
              <LinkRow
                key={check.name}
                icon={<StateIcon state={check.state} />}
                label={check.name}
                url={check.url}
              />
            ))}
          </ul>
        ) : (
          <p className="text-[13px] text-muted-foreground/70">
            {pr.state === "open" ? "No checks reported yet." : "No checks were reported."}
          </p>
        )}
      </section>

      <WorkspacePrComments comments={pr.comments} onAddComments={onAddComments} />
    </div>
  );
}
