import { writeFile, mkdir, readFile } from "node:fs/promises";
import { dirname } from "node:path";

/**
 * MCP stdio↔HTTP bridge for agents whose ACP handshake doesn't advertise
 * http MCP support. The agent spawns this script as a stdio MCP server; each
 * newline-delimited JSON-RPC message is forwarded as an HTTP POST to Pipper's
 * in-process subagent MCP server (endpoint URL in argv[2]).
 *
 * Kept as an embedded string and materialized to userData at runtime so the
 * packaged build needs no extra bundling step for a loose script asset.
 */
export const STDIO_PROXY_SOURCE = `// Generated by Pipper — MCP stdio to HTTP bridge for the subagent tool.
import { createInterface } from "node:readline";

const url = process.argv[2];
if (!url) {
  process.stderr.write("usage: subagent-stdio-proxy.mjs <endpoint-url>\\n");
  process.exit(1);
}

const rl = createInterface({ input: process.stdin, terminal: false });
rl.on("line", (line) => {
  const body = line.trim();
  if (!body) return;
  void forward(body);
});
rl.on("close", () => process.exit(0));

async function forward(body) {
  try {
    const res = await fetch(url, {
      method: "POST",
      headers: { "content-type": "application/json", accept: "application/json" },
      body,
    });
    const text = (await res.text()).trim();
    if (text) process.stdout.write(text + "\\n");
  } catch (err) {
    let id = null;
    try {
      const msg = JSON.parse(body);
      if (msg && msg.id !== undefined) id = msg.id;
    } catch {}
    if (id !== null && id !== undefined) {
      process.stdout.write(
        JSON.stringify({ jsonrpc: "2.0", id, error: { code: -32603, message: String(err) } }) + "\\n",
      );
    }
  }
}
`;

/** Write the shim to disk if missing or stale; returns the path unchanged. */
export async function ensureStdioProxyScript(path: string): Promise<string> {
  let current: string | null = null;
  try {
    current = await readFile(path, "utf-8");
  } catch {
    current = null;
  }
  if (current !== STDIO_PROXY_SOURCE) {
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, STDIO_PROXY_SOURCE, "utf-8");
  }
  return path;
}
